language: go
go:
  - 1.11.x
  - master

install:
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u github.com/golang/lint/golint
 - go get -u github.com/PuerkitoBio/goquery

script:
 - go vet ./...
 - diff <(golint ./...) <(printf "")
